= Developing AI-enabled Applications with Red{nbsp}Hat OpenShift Data Science
:navtitle: Welcome

IMPORTANT: This is not an official Red{nbsp}Hat Training course. Please contact your Red{nbsp}Hat sales representative if you want more information about Training or Guidelines about this product. You can view the list of training courses and certifications at [https://www.redhat.com/en/services/training-and-certification].

NOTE: This course is under development.

Welcome to the Red{nbsp}Hat Training quick course on building AI-enabled applications with Red{nbsp}Hat OpenShift Data Science (RHODS).

Use the links in the sidebar panel to navigate this course.

== Introduction

Companies collecting and storing vast amounts of information from multiple sources need an easy way to analyze this data, visualize trends and patterns, and experiment with predicting future business outcomes using machine learning and artificial intelligence algorithms.

This course addresses the customer need for an introduction to using RHODS, including basic concepts and tools.
After taking this course, learners should be able to perform data analysis, create learning models, and deploy them for consumption by applications.

This course is based on Red{nbsp}Hat速 OpenShift速 Container Platform {ocp-version} and Red{nbsp}Hat速 OpenShift速 Data Science {rhods-major-version}.

== Course Objectives

At a foundational level:

* Import, clean, filter and transform data from various sources
* Perform data analysis using appropriate Python libraries and data science algorithms
* Provide insights, trends and predictions from the analysis of data 
* Create and train machine learning models
* Expose the machine learning models for consumption from external applications

== Audience

* Data scientists interested in using RHODS to perform data analysis, visualization, training data sets, and serving machine learning models for consumption by applications.
* Developers who want to learn about integrating applications with RHODS to provide data analysis, data visualization, machine learning and predictive capabilities.

==  Prerequisites

* Take the Introduction to Python Programming (AD141) training course or demonstrate equivalent knowledge of Python programming
* Basics of creating and consuming HTTP REST APIs
