= Lab: Jupyter Notebooks

== Objective

* Create Jupyter notebooks to execute code, and perform data analysis interactively.

== Steps

. Log in to the RHODS console

.. Step 1.1 instructions
.. Step 1.2 instructions

. Create a new notebook

.. Step 2.1 instructions
.. Step 2.2 instructions

== Architect Notes (to be deleted in final completed version of this lab)

* Make students create a notebook from scratch
* Basic Python commands
* Show how to add and import packages/libraries to notebooks via requirements.txt
* Import a template notebook from Git and complete missing code
* Push completed notebook back to a Git repository
* Create notebooks, open consoles, upload files
* Basic cell management to run python code (create, execute, move, and delete cells)
* Ability to run shell commands with the ! prefix
* GitHub/GitLab integration
* Embedded Markdown in notebooks? Check if this is enabled by default in the RHODS packages version of Jupyter or if this can be added on using plugins and PyPi packages?


