=  RedHat OpenShift Data Science

== Why

* Operationalize the models. Data sciencits should be able to follow a solid and well stablish life cycle
* Why containers, kuberentes and devops? reproducibility and repeatibility of environrmnets (get the same results every time)
* K8s higly availiable, resilient, managed by operations team and improved by infosec (at massive scales).


Three-tier support model.

== Open Data Hub

This is the upstream project, driven by the community.


The RHODS cloud service is a subset of ODH.

RHODS is also offered as a self-managed version.


== Foundation Models

Example

== The Data Scientist Side

...

== The App Developer Side

Caikit is an AI toolkit that enables users to manage models through a set of developer friendly APIs


== GitOps for MLOps

...


== Getting Started


* If I already have OpenShift -> OperatorHub


== InstaScale

https://cloud.redhat.com/blog/ai/ml-models-batch-training-at-scale-with-open-data-hub


== Examples

Ansible LightSpeed


== Custom Workspace Images

...


== Data Science Pipelines

Data Science Pipelines are build on Tekton and many features of Kubeflow pipelines, and adding additional features such as hypterparameter tuning.
UI to build pipelines into notebooks.

== Support for Acceleration

* Nvidia GPUs
* Intel
* FPGAs?



=== References

* https://developers.redhat.com/learn/openshift-data-science[Red Hat Developers page for RHODS]
